local T = require("tests.lib")
local turn = require("rules.turn")

local function game(red, blue, max_turns)
  local s = turn.new({ "red", "blue" }, max_turns or 6)
  turn.start(s)
  turn.set_ships(s, "red", red)
  turn.set_ships(s, "blue", blue)
  return s
end

return {
  { "starts in setup, then initiative on turn 1", function()
    local s = turn.new({ "red", "blue" }, 6)
    T.eq(s.phase, turn.SETUP)
    T.truthy(turn.start(s))
    T.eq(s.turn, 1)
    T.eq(s.phase, turn.INITIATIVE)
    T.falsy(turn.start(s))
  end },
  { "sides alternate starting with initiative winner", function()
    local s = game({ "r1", "r2" }, { "b1", "b2" })
    turn.set_initiative(s, { "blue", "red" })
    T.eq(s.phase, turn.ACTIVATION)
    T.eq(s.current, "blue")
    T.truthy(turn.activate(s, "blue", "b2"))
    T.eq(s.current, "red")
    T.truthy(turn.activate(s, "red", "r1"))
    T.eq(s.current, "blue")
    T.truthy(turn.activate(s, "blue", "b1"))
    T.truthy(turn.activate(s, "red", "r2"))
    T.eq(s.phase, turn.WIND)
    T.eq(s.current, nil)
  end },
  { "side with more ships keeps activating once the other runs out", function()
    local s = game({ "r1" }, { "b1", "b2", "b3" })
    turn.set_initiative(s, { "red", "blue" })
    turn.activate(s, "red", "r1")
    T.eq(s.current, "blue")
    turn.activate(s, "blue", "b1")
    T.eq(s.current, "blue")
    turn.activate(s, "blue", "b2")
    turn.activate(s, "blue", "b3")
    T.eq(s.phase, turn.WIND)
  end },
  { "illegal activations are refused", function()
    local s = game({ "r1", "r2" }, { "b1" })
    turn.set_initiative(s, { "red", "blue" })
    local ok, msg = turn.activate(s, "blue", "b1")
    T.falsy(ok)
    T.truthy(msg:find("red"))
    T.falsy(turn.activate(s, "red", "b1"))
    turn.activate(s, "red", "r1")
    turn.activate(s, "blue", "b1")
    local ok2, msg2 = turn.activate(s, "red", "r1")
    T.falsy(ok2)
    T.truthy(msg2:find("already"))
  end },
  { "no ships at all goes straight to wind phase", function()
    local s = game({}, {})
    turn.set_initiative(s, { "red", "blue" })
    T.eq(s.phase, turn.WIND)
  end },
  { "wind phase advances the turn and clears activations", function()
    local s = game({ "r1" }, { "b1" })
    turn.set_initiative(s, { "red", "blue" })
    turn.activate(s, "red", "r1")
    turn.activate(s, "blue", "b1")
    T.truthy(turn.end_wind_phase(s))
    T.eq(s.turn, 2)
    T.eq(s.phase, turn.INITIATIVE)
    T.eq(s.order, nil)
    T.eq(#turn.remaining(s, "red"), 1)
  end },
  { "game ends after the last turn's wind phase", function()
    local s = game({}, {}, 2)
    turn.set_initiative(s, { "red", "blue" })
    turn.end_wind_phase(s)
    T.eq(s.turn, 2)
    turn.set_initiative(s, { "blue", "red" })
    turn.end_wind_phase(s)
    T.eq(s.phase, turn.OVER)
    T.eq(s.end_reason, "turns")
    T.falsy(turn.set_initiative(s, { "red", "blue" }))
  end },
  { "phase guards", function()
    local s = game({ "r1" }, { "b1" })
    T.falsy(turn.end_wind_phase(s))
    T.falsy(turn.activate(s, "red", "r1"))
  end },
}
