-- Bundles an entry script and every module it requires into one file that
-- can be pasted into (or pushed as) the TTS Global script.
--
--   lua tools/bundle.lua                       -> build/Global.lua from tts/global.lua
--   lua tools/bundle.lua tts/global.lua out.lua
local script = (arg and arg[0]) or "tools/bundle.lua"
local root = script:match("^(.*)[/\\]tools[/\\][^/\\]*$") or "."
local entry = arg[1] or "tts/global.lua"
local out_path = arg[2] or (root .. "/build/Global.lua")

local function read(path)
  local f = assert(io.open(path, "rb"), "cannot open " .. path)
  local s = f:read("*a")
  f:close()
  return s
end

local function requires(src)
  local names = {}
  for name in src:gmatch("require%s*%(?%s*[\"']([%w_%.]+)[\"']") do names[#names + 1] = name end
  return names
end

local order, seen = {}, {}
local function visit(name)
  if seen[name] then return end
  seen[name] = true
  local src = read(root .. "/" .. name:gsub("%.", "/") .. ".lua")
  for _, dep in ipairs(requires(src)) do visit(dep) end
  order[#order + 1] = { name = name, src = src }
end

local entry_src = read(root .. "/" .. entry)
for _, dep in ipairs(requires(entry_src)) do visit(dep) end

-- TTS runs MoonSharp (Lua 5.2) but tests run on 5.4, so 5.3+ features would
-- pass every test and then fail in game. Blank out comments and strings,
-- keeping newlines for line numbers, then look for them.
local function code_only(src)
  local out, i, n = {}, 1, #src
  local function blank(s) return (s:gsub("[^\n]", " ")) end
  while i <= n do
    local c = src:sub(i, i)
    local long = src:match("^%-%-%[(=*)%[", i) or src:match("^%[(=*)%[", i)
    if long then
      local close = "]" .. long .. "]"
      local _, e = src:find(close, i, true)
      e = e or n
      out[#out + 1] = blank(src:sub(i, e))
      i = e + 1
    elseif src:sub(i, i + 1) == "--" then
      local e = (src:find("\n", i, true) or n + 1) - 1
      out[#out + 1] = blank(src:sub(i, e))
      i = e + 1
    elseif c == '"' or c == "'" then
      local j = i + 1
      while j <= n and src:sub(j, j) ~= c do
        if src:sub(j, j) == "\\" then j = j + 1 end
        j = j + 1
      end
      out[#out + 1] = blank(src:sub(i, j))
      i = j + 1
    else
      out[#out + 1] = c
      i = i + 1
    end
  end
  return table.concat(out)
end

local FORBIDDEN = {
  { "//", "integer division" },
  { "%f[%w_]goto%f[^%w_]", "goto" },
  { "::[%a_][%w_]*::", "goto label" },
  { "[&|]", "bitwise operator" },
  { "~[^=]", "bitwise not/xor" },
  { "~$", "bitwise not/xor" },
  { "<<", "bit shift" },
  { ">>", "bit shift" },
  { "math%.type", "math.type" },
  { "math%.tointeger", "math.tointeger" },
  { "math%.ult", "math.ult" },
  { "utf8%.", "utf8 library" },
  { "table%.move", "table.move" },
  { "string%.pack", "string.pack" },
  { "string%.unpack", "string.unpack" },
  { "math%.atan%s*%([^()]*,", "two-argument math.atan (use math.atan2 with a fallback)" },
}

-- A line whose comment says "lua52: ok" is skipped (e.g. a guarded fallback).
local problems = {}
local function lines_of(s)
  local t = {}
  for line in (s .. "\n"):gmatch("([^\n]*)\n") do t[#t + 1] = line end
  return t
end
local function lint(label, src)
  local raw = lines_of(src)
  for ln, line in ipairs(lines_of(code_only(src))) do
    for _, f in ipairs(FORBIDDEN) do
      if line:find(f[1]) and not raw[ln]:find("lua52: ok", 1, true) then
        problems[#problems + 1] = ("%s:%d: %s (not in Lua 5.2 / MoonSharp)"):format(label, ln, f[2])
      end
    end
  end
end
for _, m in ipairs(order) do lint(m.name:gsub("%.", "/") .. ".lua", m.src) end
lint(entry, entry_src)
if #problems > 0 then
  io.stderr:write(table.concat(problems, "\n") .. "\n")
  os.exit(1)
end

local parts = {
  "-- GENERATED by tools/bundle.lua from " .. entry .. ". Do not edit; edit the sources.\n",
  "local __modules, __loaded = {}, {}\n",
  "local function require(name)\n",
  "  if __loaded[name] == nil then\n",
  "    local f = __modules[name]\n",
  "    if not f then error(\"module not found: \" .. name, 2) end\n",
  "    __loaded[name] = f(name) or true\n",
  "  end\n",
  "  return __loaded[name]\n",
  "end\n\n",
}
for _, m in ipairs(order) do
  parts[#parts + 1] = "__modules[\"" .. m.name .. "\"] = function(...)\n" .. m.src .. "\nend\n\n"
end
parts[#parts + 1] = "-- entry: " .. entry .. "\n" .. entry_src

local out_dir = out_path:match("^(.*)[/\\][^/\\]*$") or "."
if package.config:sub(1, 1) == "\\" then
  os.execute('if not exist "' .. out_dir:gsub("/", "\\") .. '" mkdir "' .. out_dir:gsub("/", "\\") .. '"')
else
  os.execute('mkdir -p "' .. out_dir .. '"')
end
local f = assert(io.open(out_path, "wb"))
f:write(table.concat(parts))
f:close()
print("wrote " .. out_path .. " (" .. #order .. " modules)")
