-- Bundles an entry script and every module it requires into one file that
-- can be pasted into (or pushed as) the TTS Global script.
--
--   lua tools/bundle.lua                       -> build/Global.lua from tts/global.lua
--   lua tools/bundle.lua tts/global.lua out.lua
local script = (arg and arg[0]) or "tools/bundle.lua"
local root = script:match("^(.*)[/\\]tools[/\\][^/\\]*$") or "."
local entry = arg[1] or "tts/global.lua"
local out_path = arg[2] or (root .. "/build/Global.lua")

local function read(path)
  local f = assert(io.open(path, "rb"), "cannot open " .. path)
  local s = f:read("*a")
  f:close()
  return s
end

local function requires(src)
  local names = {}
  for name in src:gmatch("require%s*%(?%s*[\"']([%w_%.]+)[\"']") do names[#names + 1] = name end
  return names
end

local order, seen = {}, {}
local function visit(name)
  if seen[name] then return end
  seen[name] = true
  local src = read(root .. "/" .. name:gsub("%.", "/") .. ".lua")
  for _, dep in ipairs(requires(src)) do visit(dep) end
  order[#order + 1] = { name = name, src = src }
end

local entry_src = read(root .. "/" .. entry)
for _, dep in ipairs(requires(entry_src)) do visit(dep) end

local parts = {
  "-- GENERATED by tools/bundle.lua from " .. entry .. ". Do not edit; edit the sources.\n",
  "local __modules, __loaded = {}, {}\n",
  "local function require(name)\n",
  "  if __loaded[name] == nil then\n",
  "    local f = __modules[name]\n",
  "    if not f then error(\"module not found: \" .. name, 2) end\n",
  "    __loaded[name] = f(name) or true\n",
  "  end\n",
  "  return __loaded[name]\n",
  "end\n\n",
}
for _, m in ipairs(order) do
  parts[#parts + 1] = "__modules[\"" .. m.name .. "\"] = function(...)\n" .. m.src .. "\nend\n\n"
end
parts[#parts + 1] = "-- entry: " .. entry .. "\n" .. entry_src

local out_dir = out_path:match("^(.*)[/\\][^/\\]*$") or "."
if package.config:sub(1, 1) == "\\" then
  os.execute('if not exist "' .. out_dir:gsub("/", "\\") .. '" mkdir "' .. out_dir:gsub("/", "\\") .. '"')
else
  os.execute('mkdir -p "' .. out_dir .. '"')
end
local f = assert(io.open(out_path, "wb"))
f:write(table.concat(parts))
f:close()
print("wrote " .. out_path .. " (" .. #order .. " modules)")
